// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package usecase

import (
	"fmt"
	"strings"
)

const (
	// ResolveLoginChallengeActionRedirect is a ResolveLoginChallengeAction of type Redirect.
	ResolveLoginChallengeActionRedirect ResolveLoginChallengeAction = "Redirect"
	// ResolveLoginChallengeActionRender is a ResolveLoginChallengeAction of type Render.
	ResolveLoginChallengeActionRender ResolveLoginChallengeAction = "Render"
)

var ErrInvalidResolveLoginChallengeAction = fmt.Errorf("not a valid ResolveLoginChallengeAction, try [%s]", strings.Join(_ResolveLoginChallengeActionNames, ", "))

var _ResolveLoginChallengeActionNames = []string{
	string(ResolveLoginChallengeActionRedirect),
	string(ResolveLoginChallengeActionRender),
}

// ResolveLoginChallengeActionNames returns a list of possible string values of ResolveLoginChallengeAction.
func ResolveLoginChallengeActionNames() []string {
	tmp := make([]string, len(_ResolveLoginChallengeActionNames))
	copy(tmp, _ResolveLoginChallengeActionNames)
	return tmp
}

// ResolveLoginChallengeActionValues returns a list of the values for ResolveLoginChallengeAction
func ResolveLoginChallengeActionValues() []ResolveLoginChallengeAction {
	return []ResolveLoginChallengeAction{
		ResolveLoginChallengeActionRedirect,
		ResolveLoginChallengeActionRender,
	}
}

// String implements the Stringer interface.
func (x ResolveLoginChallengeAction) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ResolveLoginChallengeAction) IsValid() bool {
	_, err := ParseResolveLoginChallengeAction(string(x))
	return err == nil
}

var _ResolveLoginChallengeActionValue = map[string]ResolveLoginChallengeAction{
	"Redirect": ResolveLoginChallengeActionRedirect,
	"redirect": ResolveLoginChallengeActionRedirect,
	"Render":   ResolveLoginChallengeActionRender,
	"render":   ResolveLoginChallengeActionRender,
}

// ParseResolveLoginChallengeAction attempts to convert a string to a ResolveLoginChallengeAction.
func ParseResolveLoginChallengeAction(name string) (ResolveLoginChallengeAction, error) {
	if x, ok := _ResolveLoginChallengeActionValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ResolveLoginChallengeActionValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ResolveLoginChallengeAction(""), fmt.Errorf("%s is %w", name, ErrInvalidResolveLoginChallengeAction)
}
