// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package usecase

import (
	"fmt"
	"strings"
)

const (
	// SyncBotStatusCreated is a SyncBotStatus of type Created.
	SyncBotStatusCreated SyncBotStatus = "Created"
	// SyncBotStatusUpdated is a SyncBotStatus of type Updated.
	SyncBotStatusUpdated SyncBotStatus = "Updated"
	// SyncBotStatusNotUpdated is a SyncBotStatus of type NotUpdated.
	SyncBotStatusNotUpdated SyncBotStatus = "NotUpdated"
)

var ErrInvalidSyncBotStatus = fmt.Errorf("not a valid SyncBotStatus, try [%s]", strings.Join(_SyncBotStatusNames, ", "))

var _SyncBotStatusNames = []string{
	string(SyncBotStatusCreated),
	string(SyncBotStatusUpdated),
	string(SyncBotStatusNotUpdated),
}

// SyncBotStatusNames returns a list of possible string values of SyncBotStatus.
func SyncBotStatusNames() []string {
	tmp := make([]string, len(_SyncBotStatusNames))
	copy(tmp, _SyncBotStatusNames)
	return tmp
}

// SyncBotStatusValues returns a list of the values for SyncBotStatus
func SyncBotStatusValues() []SyncBotStatus {
	return []SyncBotStatus{
		SyncBotStatusCreated,
		SyncBotStatusUpdated,
		SyncBotStatusNotUpdated,
	}
}

// String implements the Stringer interface.
func (x SyncBotStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SyncBotStatus) IsValid() bool {
	_, err := ParseSyncBotStatus(string(x))
	return err == nil
}

var _SyncBotStatusValue = map[string]SyncBotStatus{
	"Created":    SyncBotStatusCreated,
	"created":    SyncBotStatusCreated,
	"Updated":    SyncBotStatusUpdated,
	"updated":    SyncBotStatusUpdated,
	"NotUpdated": SyncBotStatusNotUpdated,
	"notupdated": SyncBotStatusNotUpdated,
}

// ParseSyncBotStatus attempts to convert a string to a SyncBotStatus.
func ParseSyncBotStatus(name string) (SyncBotStatus, error) {
	if x, ok := _SyncBotStatusValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _SyncBotStatusValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return SyncBotStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidSyncBotStatus)
}
